config/routes.rb
SYDE322Server4a::Application.routes.draw do
  root to: 'static_pages#home'

  resources :songs

  resources :user_games

  resources :games

  resources :users

end

app/models/song.rb
class Song < ActiveRecord::Base
   validates :name, presence: true, uniqueness: true
   #has_many :id, :class_name => "Game", :f 
   has_many :games
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json
  def index
    # @songs = Song.all
    @songs = if params[:name]
      Song.find_all_by_name(params[:name])
    elsif params[:id]
      Song.find_all_by_id(params[:id])
    elsif params[:artist]
      Song.find_all_by_artist(params[:artist])
    else
      Song.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :lyrics %><br />
    <%= f.text_field :lyrics %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table class="table table-striped" >
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Artist</th>
    <th>Lyrics</th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
   <tr>
    <td><%= song.id %></td>
    <td><%= song.name %></td>
    <td><%= song.artist %></td>
    <td><%= song.lyrics %></td>
    <td><%= link_to 'Show', song, class: "btn btn-small" %>
    <%= link_to 'Edit', edit_song_path(song), class: "btn btn-small" %>
    <%= link_to 'Destroy', song, confirm: 'Are you sure?', method: :delete, class: "btn btn-small" %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_song_path, class: "btn btn-large btn-primary page_button"  %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @song.name %>
</p>

<p>
  <b>Artist:</b>
  <%= @song.artist %>
</p>

<p>
  <b>Lyrics:</b>
  <%= @song.lyrics %>
</p>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>