config/routes.rb
SYDE322Server4a::Application.routes.draw do
  root to: 'static_pages#home'

  resources :songs

  resources :user_games

  resources :games

  resources :users

end

app/models/game.rb
class Game < ActiveRecord::Base
   validates :name, presence: true, uniqueness: true
   #belongs_to :song_id, :class_name => "Song", :foreign_key => 'id'
   belongs_to :song
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
   # @games = Game.all
    @games = if params[:name]
      Game.find_all_by_name(params[:name])
    elsif params[:id]
      Game.find_all_by_id(params[:id])
    elsif params[:open]
      Game.find_all_by_open(params[:open])
    else
      Game.all
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :open %><br />
    <%= f.check_box :open %>
  </div>
   <div class="field">
    <%= f.label :Song_ID %><br />
    <%= f.text_field :song_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Game Rooms</h1>

<table class="table table-striped">
   <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Open</th>
    <th>SongID</th>    
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.id %></td>     
    <td><%= game.name %></td>
    <td><%= game.open %></td>
    <td><%= game.song_id %></td>    
    <td><%= link_to 'Show', game, class: "btn btn-small" %>
    <%= link_to 'Edit', edit_game_path(game), class: "btn btn-small" %>
    <%= link_to 'Destroy', game, confirm: 'Are you sure?', method: :delete, class: "btn btn-small" %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path, class: "btn btn-large btn-primary page_button" %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @game.name %>
</p>

<p>
  <b>Open:</b>
  <%= @game.open %>
</p>

<p>
  <b>Song_id:</b>
  <%= @game.song_id %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>