config/routes.rb
SYDE322Server4a::Application.routes.draw do
  root to: 'static_pages#home'

  resources :songs

  resources :user_games

  resources :games

  resources :users

end

app/models/user_game.rb
class UserGame < ActiveRecord::Base
end

app/controllers/user_games_controller.rb
class UserGamesController < ApplicationController
  # GET /user_games
  # GET /user_games.json
  def index
#    @user_games = UserGame.all
    @user_games = if params[:user]
      UserGame.find_all_by_user_id(params[:user])
    elsif params[:game]
      UserGame.find_all_by_game_id(params[:game])
    else
      UserGame.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_games }
    end
  end

  # GET /user_games/1
  # GET /user_games/1.json
  def show
    @user_game = UserGame.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_game }
    end
  end

  # GET /user_games/new
  # GET /user_games/new.json
  def new
    @user_game = UserGame.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_game }
    end
  end

  # GET /user_games/1/edit
  def edit
    @user_game = UserGame.find(params[:id])
  end

  # POST /user_games
  # POST /user_games.json
  def create
    @user_game = UserGame.new(params[:user_game])

    respond_to do |format|
      if @user_game.save
        format.html { redirect_to @user_game, notice: 'User game was successfully created.' }
        format.json { render json: @user_game, status: :created, location: @user_game }
      else
        format.html { render action: "new" }
        format.json { render json: @user_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_games/1
  # PUT /user_games/1.json
  def update
    @user_game = UserGame.find(params[:id])

    respond_to do |format|
      if @user_game.update_attributes(params[:user_game])
        format.html { redirect_to @user_game, notice: 'User game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_games/1
  # DELETE /user_games/1.json
  def destroy
    @user_game = UserGame.find(params[:id])
    @user_game.destroy

    respond_to do |format|
      format.html { redirect_to user_games_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_games_helper.rb
module UserGamesHelper
end

app/views/user_games/_form.html.erb
<%= form_for(@user_game) do |f| %>
  <% if @user_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_game.errors.count, "error") %> prohibited this user_game from being saved:</h2>

      <ul>
      <% @user_game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :game_score %><br />
    <%= f.number_field :game_score %>
  </div>
  <div class="field">
    <%= f.label :isAdmin %><br />
    <%= f.check_box :isAdmin %>
  </div>
  <div class="field">
    <%= f.label :isWinner %><br />
    <%= f.check_box :isWinner %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_games/edit.html.erb
<h1>Editing user_game</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_game %> |
<%= link_to 'Back', user_games_path %>

app/views/user_games/index.html.erb
<h1>Listing user_games</h1>

<table class="table table-stripped">
  <tr>
    <th>User</th>
    <th>Game</th>
    <th>Game score</th>
    <th>Isadmin</th>
    <th>Iswinner</th>
    <th></th>
  </tr>

<% @user_games.each do |user_game| %>
  <tr>
    <td><%= user_game.user_id %></td>
    <td><%= user_game.game_id %></td>
    <td><%= user_game.game_score %></td>
    <td><%= user_game.isAdmin %></td>
    <td><%= user_game.isWinner %></td>
    <td><%= link_to 'Show', user_game, class: "btn btn-small" %>
    <%= link_to 'Edit', edit_user_game_path(user_game), class: "btn btn-small" %>
    <%= link_to 'Destroy', user_game, confirm: 'Are you sure?', method: :delete, class: "btn btn-small" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User game', new_user_game_path, class: "btn btn-large btn-primary page_button" %>

app/views/user_games/new.html.erb
<h1>New user_game</h1>

<%= render 'form' %>

<%= link_to 'Back', user_games_path %>

app/views/user_games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_game.user_id %>
</p>

<p>
  <b>Game:</b>
  <%= @user_game.game_id %>
</p>

<p>
  <b>Round score:</b>
  <%= @user_game.game_score %>
</p>

<p>
  <b>Isadmin:</b>
  <%= @user_game.isAdmin %>
</p>

<p>
  <b>Iswinner:</b>
  <%= @user_game.isWinner %>
</p>


<%= link_to 'Edit', edit_user_game_path(@user_game) %> |
<%= link_to 'Back', user_games_path %>